### ISSUE TITLE
アイテムを削除したときに落ちる

### ISSUE THREAD

**Issue by Khromium** [Khromium/PriManager#44]
多分　#43 と関連してる
データを削除したときにページングデータが更新していないことが原因で発生しているっぽい
```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: work.airz.primanager, PID: 6435
                  android.database.sqlite.SQLiteException: parseSingle accepts only cursors with a single entry
                      at org.jetbrains.anko.db.SqlParsersKt.parseSingle(SqlParsers.kt:66)
                      at work.airz.primanager.db.DBUtil$getFollowTicket$1$1.invoke(DBUtil.kt:53)
                      at work.airz.primanager.db.DBUtil$getFollowTicket$1$1.invoke(DBUtil.kt:17)
                      at org.jetbrains.anko.db.SelectQueryBuilder.exec(SelectQueryBuilder.kt:44)
                      at work.airz.primanager.db.DBUtil$getFollowTicket$1.invoke(DBUtil.kt:52)
                      at work.airz.primanager.db.DBUtil$getFollowTicket$1.invoke(DBUtil.kt:17)
                      at org.jetbrains.anko.db.ManagedSQLiteOpenHelper.use(Database.kt:177)
                      at work.airz.primanager.db.DBUtil.getFollowTicket(DBUtil.kt:51)
                      at work.airz.primanager.MainActivity$onItemPager$1.onDBImage(MainActivity.kt:83)
                      at work.airz.primanager.TicketListPager.getList(TicketListPager.kt:59)
                      at work.airz.primanager.TicketListPager.getPagedList(TicketListPager.kt:43)
                      at work.airz.primanager.RecyclarViewAdapter$deleteSelected$$inlined$apply$lambda$1.onClick(RecyclarViewAdapter.kt:100)
                      at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6494)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by Khromium** [comment]
直ったのでcloseします
